name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master
jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup-node
        uses: actions/setup-node@master
      - name: Build
        run: |
          npm install
          npm run build:prod
      - name: deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MONET_AF14E}}
